services:
  api:
    build: .
    environment:
      POSTGRES_CONN_STR: ${POSTGRES_CONN_STR}
    depends_on:
      - database
    ports:
      - "8080:8080"

  database:
    image: postgres
    environment:
      POSTGRES_DB:  ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data


volumes:
  db_data: